//session
export const AUTH_SESS = 'AUTH_SESS';
export const END_SESS = 'END_SESS';
export const SET_CURRENT_COMPANY = 'SET_CURRENT_COMPANY';
export const SET_CURRENT_TASK = 'SET_CURRENT_TASK';
//updates
export const SET_UPDATES = 'SET_UPDATES';
//user
export const GET_USER = 'GET_USER';
export const REMOVE_USER = 'REMOVE_USER ';
//profile
export const GET_PROFILE = 'GET_PROFILE';
export const REMOVE_PROFILE = 'REMOVE_PROFILE ';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

//messages
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_ERROR = 'SET_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const CLEAR_ALL_ERRORS = 'CLEAR_ALL_ERRORS';
//companies
export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES';
export const CLEAR_COMPANIES = 'CLEAR_COMPANIES';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
//invoice
export const SET_INVOICE_INIT_STATE = 'SET_INVOICE_INIT_STATE';
export const CHANGE_INVOICE_COLORS = 'CHANGE_INVOICE_COLORS';
export const UPDATE_INVOICE_PROFILE = 'UPDATE_INVOICE_PROFILE';
export const UPDATE_INVOICE_COMPANY = 'UPDATE_INVOICE_COMPANY';
export const UPDATE_INVOICE_ISSUE_DATE = 'UPDATE_INVOICE_ISSUE_DATE';
export const UPDATE_INVOICE_DUE_DATE = 'UPDATE_INVOICE_DUE_DATE';
