const { v4: uuidv4 } = require('uuid');
export const companyInitDetails = [
    {
        _id: uuidv4(),
        label: 'Name',
        value: '',
        addToInvoice: true,
        custom: false,
        inputType: 'text',
        required: true,
    },
    {
        _id: uuidv4(),
        label: 'Email',
        value: '',
        addToInvoice: true,
        custom: false,
        inputType: 'text',
        validate: {
            type: 'isEmail',
            msg: 'Please enter a valid email address in format xxxx@xxx.xxx .',
        },
    },
    {
        _id: uuidv4(),
        label: 'Website',
        value: '',
        addToInvoice: true,
        custom: false,
        inputType: 'text',
    },
    {
        _id: uuidv4(),
        label: 'Phone',
        value: '',
        addToInvoice: true,
        custom: false,
        inputType: 'text',
    },
    {
        _id: uuidv4(),
        label: 'Address Line 1',
        value: '',
        addToInvoice: true,
        custom: false,
        inputType: 'text',
    },
    {
        _id: uuidv4(),
        label: 'Address Line 2',
        value: '',
        addToInvoice: true,
        custom: false,
        inputType: 'text',
    },
    {
        _id: uuidv4(),
        label: 'City',
        value: '',
        addToInvoice: true,
        custom: false,
        inputType: 'text',
    },
    {
        _id: uuidv4(),
        label: 'County',
        value: '',
        addToInvoice: true,
        custom: false,
        inputType: 'text',
    },
    {
        _id: uuidv4(),
        label: 'Postcode',
        value: '',
        addToInvoice: true,
        custom: false,
        inputType: 'text',
    },
    {
        _id: uuidv4(),
        label: 'Bank Name',
        value: '',
        addToInvoice: true,
        custom: false,
        inputType: 'text',
    },
    {
        _id: uuidv4(),
        label: 'Sort Code',
        value: '',
        addToInvoice: true,
        custom: false,
        inputType: 'text',
    },
    {
        _id: uuidv4(),
        label: 'Account Number',
        value: '',
        addToInvoice: true,
        custom: false,
        inputType: 'text',
        validate: {
            type: 'isNumber',
            msg: 'Account Number must contain only numerical values.',
        },
    },
    {
        _id: uuidv4(),
        label: 'Notes',
        value: '',
        addToInvoice: false,
        custom: false,
        inputType: 'textarea',
    },
];
